### ISSUE TITLE
Unclear instructions in README

### ISSUE THREAD

**Issue by brunobeeee** [DevLARLEY/amzn-480p-downloader#2]
Hello I have problems understanding the instructions given in the readme file. Especially 2. and 3.

> 2. Drop the file in either of those 

Wich file in which "of those"?

> 3. Add an L3 CDM in the right folder

Wich folder ist the right one? Is the L3 CDM the `device_private_key` and `device_client_id_blob`?

Thank you!

Edit: Typo

**Comment by DevLARLEY** [comment]
"the file" is referring to either [amzn_480p_pywidevine.py](https://github.com/DevLARLEY/amzn-480p-downloader/blob/main/amzn_480p_pywidevine.py) or [amzn_480p_wks.py](https://github.com/DevLARLEY/amzn-480p-downloader/blob/main/amzn_480p_wks.py).
if you want to use the wks file, you'd have to download [WKS-KEYS](https://github.com/SASUKE-DUCK/WKS-KEY/releases) and drop the file [amzn_480p_wks.py](https://github.com/DevLARLEY/amzn-480p-downloader/blob/main/amzn_480p_wks.py) into the WKS-KEYS folder.

And yes, the L3 CDM is "device_private_key" and "device_client_id_blob".
for wks, it'll go into WKS-KEYS\pywidevine\L3\cdm\devices\android_generic and for pywidevine in the Devices folder

**Comment by ThatNotEasy** [comment]
this one is very slow, got any alternative?
```
pssh = None
mpd_url = None
for u in urls:
    m = urls[u]["urls"]["manifest"]["url"]
    logging.info(m)
    mpd = requests.get(url=m, headers=headers)
    if mpd.status_code == 200:
        res = re.findall('<cenc:pssh.*>.*<.*/cenc:pssh>', mpd.text)
        pssh = str(min([x[11:-12] for x in res], key=len)).split(">")[-1].split("<")[-1] if res else None
        if pssh is not None:
            break
```

and what different about mpd such as
```
{mpd_url}
```
and
```
{mpd_url}/?amznDtid=AOAGZA014O5RE&encoding=segmentBase
```
and when i tried out to append "?amznDtid=AOAGZA014O5RE&encoding=segmentBase", the return i got
![Screenshot_9](https://github.com/DevLARLEY/amzn-480p-downloader/assets/25004320/2ec92f0a-2d3b-4852-8464-fb2621b09f0f)
 maybe the params was changed while use "?amznDtid=AOAGZA014O5RE&encoding=segmentBase"
