### ISSUE TITLE
Wrong Playlist?

### ISSUE THREAD

**Issue by Lostion1** [DevLARLEY/amzn-480p-downloader#5]
So i tested the script with Freevee https://www.amazon.de/gp/video/detail/B0CVF7DVQ7/

For some reason it always loads the HD playlist? With an "untrusted_device" error?
![test1](https://github.com/user-attachments/assets/7acdc1d7-a765-4228-b92a-10e9fe498165)

I think its because of the "HD" Playlist instead of the "SD" Playlist?

Also get an "Cannot complete request." Error when Using an L1 key also not sure why? :D i tested some public L1 keys and got "untrusted_device" Errors so it seems that my L1 key is working but stops with  "Cannot complete request."

![test 2](https://github.com/user-attachments/assets/ae4d79d5-4c9e-4f1e-8552-96b2d4b29b7a)

Great tool btw!

**Comment by DevLARLEY** [comment]
First of all: By 'L1 Key' you're probably referring to an L1 CDM. And all (100%) of public L1 CDMs are banned. That's why you're getting an untrusted_device error.
Also, just ignore what the request is saying. It's requesting 480p even though it says 'HD' and 1080p (as long as you haven't edited the script). 

You were probably using a public L3 CDM, that's probably also banned. 'Generate' your own one [here](https://forum.videohelp.com/threads/408031-Dumping-Your-own-L3-CDM-with-Android-Studio).
I'll get back to you when I have more time.

**Comment by Lostion1** [comment]
Oh didn't know the virtual keys are working i thought amazon banned them too.

Yeah the L1 Key was from a friend but i don't where he got it from. Maybe i try to extract my own key from my smartphone but maybe thanks for the info with the virtual keys will try that later :)

**Comment by Lostion1** [comment]
Some interesting news:

If you change:

"&deviceBitrateAdaptationsOverride=CVBR" +

to 

"&deviceBitrateAdaptationsOverride=CBR" +

you get way better Video but worse audio:

CVBR: 704x396 | 1300 Kbps | Audio: 192 Kbps = 370 MB
CBR: 720x404 | 2000 Kbps | Audio: 128 Kbps = 613 MB

Die CBR Picture is WAY better compared to the CVBR one. 

I tried CVBR,CBR because i hoped i could combine the best picture and the best audio but thats not possible. :/

**Comment by DevLARLEY** [comment]
Some comparison images:
CBR and then CVBR
![cbr_0](https://github.com/user-attachments/assets/414ec4af-a774-4d56-bfb1-5563e473e12a)
![cvbr_0](https://github.com/user-attachments/assets/a02c4b0d-7fe3-46bd-b173-36004f4bbed2)
![cbr_1](https://github.com/user-attachments/assets/5a96d013-cce6-4ed5-94ba-3acfdb941d66)
![cvbr_1](https://github.com/user-attachments/assets/37057e04-b6cd-47c0-836c-5e488190800d)
![cbr_2](https://github.com/user-attachments/assets/2e2c7f44-dc24-40a4-bd17-12df0b760c0b)
![cvbr_2](https://github.com/user-attachments/assets/72493e22-2301-4a45-9431-be3e7ff1255c)

**Comment by DevLARLEY** [comment]
Regarding this:
> I tried CVBR,CBR because i hoped i could combine the best picture and the best audio but thats not possible. :/

The comma syntax is indeed not possible, but you could remove the '-sv best -sa best -M format=mkv' from the N_m3u8DL-RE command and download your content with CBR for video and CVBR for audio.

**Comment by Lostion1** [comment]
Hm 960x480 isnt even showing up with my account. 720x404 was the highest, maybe because i only tested freevee?

**Comment by DevLARLEY** [comment]
That '720x404' resolution must be specific to your series. The season I downloaded (and the one the screenshots were from) is also from freevee.
