### ISSUE TITLE
running python amzn_480p_wks.py please help!!

### ISSUE THREAD

**Issue by Kh4N02** [DevLARLEY/amzn-480p-downloader#6]
Hi brother, could you please share pywidevine?

I'm currently using WSK_KEYS but having issues, my folder looks like this:
![image](https://github.com/user-attachments/assets/ac94c3e8-f78b-4ba0-b7ef-e84727f10f6c)

and I have added in folder device.wvd and replaced device_client_id_blob and device_private_key just in case.

my headers.py looks like this:
```
# amazon uk
cookies = {
    'ubid-acbuk': '',
    'x-acbuk': '""',
    'at-acbuk': ''
}
```
and when running command python amzn_480p_wks.py, I get this error:
Traceback (most recent call last):
  File "D:\Scripts\WKS-KEYS\amzn_480p_wks.py", line 7, in <module>
    from pywidevine.L3.cdm import deviceconfig
ModuleNotFoundError: No module named 'pywidevine.L3'

Could you please help? Am I doing something wrong? If its a stupid mistake I'm sorry 😭

**Comment by DevLARLEY** [comment]
I will re-do that script soon, but for now: **Don't post your amazon cookies publically!!!**

**Comment by Kh4N02** [comment]
Thanks, I'm beginner didn't know 👍

**Comment by Kh4N02** [comment]
thanks, will it work for prime video though? if you could explain the steps if you got time 😄

**Comment by DevLARLEY** [comment]
You can look at the installation and usage instructions on its GitHub page: https://github.com/DevLARLEY/WidevineFetch/tree/main?tab=readme-ov-file#installation
There's also a video at the bottom showing how to use it.
To find the license URL for amazon, filter with `regexp:https://.*\.(amazon|primevideo)\..*/cdp/catalog/GetPlaybackResources\?.*desiredResources=.*Widevine2License.*` and click 'Copy -> Copy as Fetch **(Node.js)**'
The Node.js option is only available in chromium-based browsers

**Comment by Kh4N02** [comment]
followed all the steps, thats the issue I get https://streamable.com/lmn3p7

**Comment by Kh4N02** [comment]
edit: I got it, love you brother ❤️ just changed device.wvd file

**Comment by DevLARLEY** [comment]
This solution will always work (as long as amazon doesn't change anything about their licensing system)
PS: You don't have to paste the fetch string. That LineEdit box is for entering the PSSH manually (not required for amazon)

Getting higher quality requires files that both of us don't have access to. The `amzn-480p-downloader` also would've only given you 480p (as the name suggests).

**Comment by Kh4N02** [comment]
yes just was over-excited, sorry for being dumb.
2 weeks I've been researching about it, and finally I got to you, now next step is somehow be able to get it high quality 😈 ❤️

**Comment by DevLARLEY** [comment]
good luck

**Comment by Kh4N02** [comment]
bro I've found this: https://github.com/ThatNotEasy/Widevine-KSKEY/releases/tag/2.3 

owner of script said me to change in the services prime.py accordingly and add headers/params and I should be able to run it and get kets, as beginner I'm unable to do so, if by chance you are able to, please help! 😘

**Comment by DevLARLEY** [comment]
1. This issue is closed
2. Don't ask for help regarding a different script on this GitHub page

**Comment by Kh4N02** [comment]
sorry, saw your posts on the forum and saw you are in search of downloading 1080p as well, tried to help you! 😄

**Comment by DevLARLEY** [comment]
It's not the downloader that enables you to get 1080p

**Comment by DevLARLEY** [comment]
It's not the downloader that enables you to get 1080p
