### ISSUE TITLE
396p instead 540p

### ISSUE THREAD

**Issue by lfer94** [DevLARLEY/amzn-480p-downloader#7]
Some videos do not have 480p resolution and the script downloads them in a lower resolution (usually 704x396). Is it possible to make it download in 960x540? It's assumed that with L3 it's possible.

Here is an example (argentina vpn is needed):

`amzn1.dv.gti.1c4ae8c5-942d-4914-9c77-762d89c22c14`

`# amazon.com
cookies = {
    'ubid-main': '130-6390668-5196830',
    'x-main': '"EUPBR0DoziBRPiE?ZstdfkUTWElMQQi99jtnlXdzUay5Q8PgLr0HUh53FlQp1m?G"',
    'at-main': 'Atza|IwEBICCL0TirKIc8BSVeh3NgP8XTZmewtIqw8Sg6-BNmEQBGpo4csiv486_T6LOTxchF3lPqaQvZJjPu_cGcZe_lEdE_NYLos81HQvLdAS39f6ouElNpDj30-DOSm4NXD-R9VySSNU47vFj70Y0ZYc_ijGOOsdhz8vme2FVb52V7ZfNjxb6-cLM9Hk7CK7caK8C_1fmwGWe-H0JUWnYmx58ZCsIsqNdAYgmZjRgmgABMyGByARP-ro3PZgpjeM-eSIBiUh8'
}`

**Comment by DevLARLEY** [comment]
The downloader doesn't do 540p, only 480p. So 396p is the max you can get because it's probably some slightly off-scale video

**Comment by lfer94** [comment]
Yes, I just realized that the manifests on android devices do not have 540p resolution, which is curious because 540p and 480p have the same width and bitrate on amzn.
